koalamon_gecko_board_home:
    path:     /p/{project}/admin/geckoboard/
    defaults: { _controller: KoalamonGeckoBoardBundle:Default:index }

koalamon_gecko_board_linechart:
    path:     /geckoboard/linechart/{eventIdentifier}/
    defaults: { _controller: KoalamonGeckoBoardBundle:LineChart:render }

koalamon_gecko_board_compare:
    path:     /geckoboard/comparison/{eventIdentifier}/
    defaults: { _controller: KoalamonGeckoBoardBundle:ComparisonChart:render }

koalamon_gecko_board_trendline:
    path:     /geckoboard/trendline/{eventIdentifier}/
    defaults: { _controller: KoalamonGeckoBoardBundle:TrendlineChart:render }
